import os
from dotenv import load_dotenv

load_dotenv() 

SUPABASE_URL=os.getenv("SUPABASE_URL")
SUPABASE_KEY=os.getenv("SUPABASE_KEY")
DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1481895784575144008/PSMg3NyBpFMgOgwIWEXbPc1Kd50W_iEHNQzJrDKnfnPcnLpKlc-1qQE1mCP_vtVwlQkg"

JWT_SECRET = "SUPER_SECRET_KEY"
JWT_ALGORITHM = "HS256"

ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 7